function T = collapse_recirculation_to_table(allCollapseRecirculation)
%COLLAPSE_RECIRCULATION_TO_TABLE  Convert collapse-recirculation results to a case summary table.

if isempty(allCollapseRecirculation)
    T = table();
    return;
end

nCases = numel(allCollapseRecirculation);
headers = { ...
    'Case','Re','kD', ...
    'nCollapseEvents', ...
    'nCollapseEventsWithGeneratedMicrobubbles', ...
    'nCollapseGeneratedMicrobubbles', ...
    'collapseGeneratedPerCollapse', ...
    'nCollapseGeneratedLeftMoving', ...
    'pctCollapseGeneratedLeftMoving_ofGenerated', ...
    'nTotalLeftMovingTracks', ...
    'pctLeftMovingFromCollapseEvents', ...
    'nCollapseGeneratedActivationEvents', ...
    'pctCollapseGeneratedActivation_ofGenerated', ...
    'nTotalActivationEvents', ...
    'pctActivationFromCollapseEvents', ...
    'matchMinFrameLag', ...
    'matchMaxFrameLag', ...
    'matchMaxDistance_mm', ...
    'microbubbleStartAreaMin_px2', ...
    'microbubbleStartAreaMax_px2'};

rows = cell(nCases, numel(headers));
for ci = 1:nCases
    rec = get_recirc_data(allCollapseRecirculation(ci));
    if isempty(rec)
        rows(ci,:) = [{string(get_case_field(allCollapseRecirculation(ci), 'caseName', ""))}, ...
            {get_case_field(allCollapseRecirculation(ci), 'Re', NaN)}, ...
            {get_case_field(allCollapseRecirculation(ci), 'kD', NaN)}, ...
            repmat({NaN}, 1, numel(headers) - 3)];
        continue;
    end

    rows(ci,:) = { ...
        string(get_field_value(rec, 'caseName', get_case_field(allCollapseRecirculation(ci), 'caseName', ""))), ...
        get_field_value(rec, 'Re', get_case_field(allCollapseRecirculation(ci), 'Re', NaN)), ...
        get_field_value(rec, 'kD', get_case_field(allCollapseRecirculation(ci), 'kD', NaN)), ...
        get_field_value(rec, 'nCollapseEvents', NaN), ...
        get_field_value(rec, 'nCollapseEventsWithGeneratedMicrobubbles', NaN), ...
        get_field_value(rec, 'nCollapseGeneratedMicrobubbles', NaN), ...
        get_field_value(rec, 'collapseGeneratedPerCollapse', NaN), ...
        get_field_value(rec, 'nCollapseGeneratedLeftMoving', NaN), ...
        get_field_value(rec, 'pctCollapseGeneratedLeftMoving_ofGenerated', NaN), ...
        get_field_value(rec, 'nTotalLeftMovingTracks', NaN), ...
        get_field_value(rec, 'pctLeftMovingFromCollapseEvents', NaN), ...
        get_field_value(rec, 'nCollapseGeneratedActivationEvents', NaN), ...
        get_field_value(rec, 'pctCollapseGeneratedActivation_ofGenerated', NaN), ...
        get_field_value(rec, 'nTotalActivationEvents', NaN), ...
        get_field_value(rec, 'pctActivationFromCollapseEvents', NaN), ...
        get_field_value(rec, 'matchMinFrameLag', NaN), ...
        get_field_value(rec, 'matchMaxFrameLag', NaN), ...
        get_field_value(rec, 'matchMaxDistance_mm', NaN), ...
        get_field_value(rec, 'microbubbleStartAreaMin_px2', NaN), ...
        get_field_value(rec, 'microbubbleStartAreaMax_px2', NaN)};
end

T = cell2table(rows, 'VariableNames', headers);
end


% =========================================================================
function rec = get_recirc_data(entry)
rec = [];
if isstruct(entry)
    if isfield(entry, 'data')
        rec = entry.data;
    else
        rec = entry;
    end
end
end


% =========================================================================
function val = get_case_field(entry, fieldName, defaultVal)
val = defaultVal;
if isstruct(entry) && isfield(entry, fieldName) && ~isempty(entry.(fieldName))
    val = entry.(fieldName);
end
end


% =========================================================================
function val = get_field_value(s, fieldName, defaultVal)
val = defaultVal;
if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
    val = s.(fieldName);
end
end
