function T = lagrangian_acceleration_to_table(allLagAccel)
%LAGRANGIAN_ACCELERATION_TO_TABLE  Convert acceleration results to summary CSV table.

if isempty(allLagAccel)
    T = table();
    return;
end

headers = { ...
    'Case','Re','kD','dMean_um','U_ref_m_s', ...
    'nTracksUsable','nActivatedTracksUsable','nNonActivatedTracksUsable', ...
    'nAllAccelSamples','nActivatedAllSamples','nNonActivatedAllSamples', ...
    'nActivatedTriggerSamples','nNonActivatedRandomSamples','nPeakGrowthPairs', ...
    'nStationaryTracks','nStationarySamples', ...
    'activatedAllMedianAstar','activatedAllP90Astar', ...
    'nonActivatedAllMedianAstar','nonActivatedAllP90Astar', ...
    'activatedTriggerMedianAstar','activatedTriggerP90Astar', ...
    'nonActivatedRandomMedianAstar','nonActivatedRandomP90Astar', ...
    'stationaryP95Astar','sgWindowFrames','sgPolyOrder','triggerWindowFrames','trackPopulation'};

nCases = numel(allLagAccel);
rows = cell(nCases, numel(headers));
for i = 1:nCases
    s = struct();
    if isfield(allLagAccel(i), 'summary') && isstruct(allLagAccel(i).summary)
        s = allLagAccel(i).summary;
    end
    rows(i,:) = { ...
        string(get_field_value(s, 'Case', get_field_value(allLagAccel(i), 'caseName', ""))), ...
        get_field_value(s, 'Re', get_field_value(allLagAccel(i), 'Re', NaN)), ...
        get_field_value(s, 'kD', get_field_value(allLagAccel(i), 'kD', NaN)), ...
        get_field_value(s, 'dMean_um', NaN), ...
        get_field_value(s, 'U_ref_m_s', NaN), ...
        get_field_value(s, 'nTracksUsable', NaN), ...
        get_field_value(s, 'nActivatedTracksUsable', NaN), ...
        get_field_value(s, 'nNonActivatedTracksUsable', NaN), ...
        get_field_value(s, 'nAllAccelSamples', NaN), ...
        get_field_value(s, 'nActivatedAllSamples', NaN), ...
        get_field_value(s, 'nNonActivatedAllSamples', NaN), ...
        get_field_value(s, 'nActivatedTriggerSamples', NaN), ...
        get_field_value(s, 'nNonActivatedRandomSamples', NaN), ...
        get_field_value(s, 'nPeakGrowthPairs', NaN), ...
        get_field_value(s, 'nStationaryTracks', NaN), ...
        get_field_value(s, 'nStationarySamples', NaN), ...
        get_field_value(s, 'activatedAllMedianAstar', NaN), ...
        get_field_value(s, 'activatedAllP90Astar', NaN), ...
        get_field_value(s, 'nonActivatedAllMedianAstar', NaN), ...
        get_field_value(s, 'nonActivatedAllP90Astar', NaN), ...
        get_field_value(s, 'activatedTriggerMedianAstar', NaN), ...
        get_field_value(s, 'activatedTriggerP90Astar', NaN), ...
        get_field_value(s, 'nonActivatedRandomMedianAstar', NaN), ...
        get_field_value(s, 'nonActivatedRandomP90Astar', NaN), ...
        get_field_value(s, 'stationaryP95Astar', NaN), ...
        get_field_value(s, 'sgWindowFrames', NaN), ...
        get_field_value(s, 'sgPolyOrder', NaN), ...
        get_field_value(s, 'triggerWindowFrames', NaN), ...
        string(get_field_value(s, 'trackPopulation', ""))};
end

T = cell2table(rows, 'VariableNames', headers);
end


% =========================================================================
function val = get_field_value(s, fieldName, defaultVal)
val = defaultVal;
if isstruct(s) && isfield(s, fieldName) && ~isempty(s.(fieldName))
    val = s.(fieldName);
end
end
