%% k/d vs Flow Rate Plot (Publication Quality)

% -------------------------------------------------------
% Input Data
% -------------------------------------------------------
kD = [0.03 0.08 0.141 0.267 0.444 0.72];
xPos = 1:numel(kD);
flowrate_lpm = [47.5 50 51 52.3 54.5 53.5];
flowrate_err_lpm = 0.25 * ones(size(flowrate_lpm));

labels   = 'Flow Rate';
savePath = 'G:\My Drive\Research\cavitation\My research papers\Pre-Cavitation dynamics of the nuclei\inkscape';
plotTitle = 'k/d vs Flow Rate';
xlab = '$k/d$';
ylab = 'Flow Rate (Lit/min)';

% -------------------------------------------------------
% Create Figure (normal visible figure)
% -------------------------------------------------------
F = figure('Color','white','Position',[200 200 900 600]);
set(F, 'DefaultTextFontName','Times New Roman', ...
       'DefaultAxesFontName','Times New Roman');
hold on;

% Scientific deep blue
col = [0 0.2 0.8];

% Plot
errorbar(xPos, flowrate_lpm, flowrate_err_lpm, ...
    '-o', ...
    'LineWidth', 3.3, ...
    'CapSize', 14, ...
    'MarkerSize', 12, ...
    'MarkerFaceColor', col, ...
    'MarkerEdgeColor', [0 0 0], ...
    'Color', [0 0 0], ...
    'DisplayName', labels);

plot(xPos, flowrate_lpm, ...
    '-o', ...
    'LineWidth', 3.3, ...
    'MarkerSize', 12, ...
    'MarkerFaceColor', col, ...
    'MarkerEdgeColor', [0 0 0], ...
    'Color', col, ...
    'HandleVisibility', 'off');

% Axis Padding
xlim([0.5, numel(kD) + 0.5]);
ylim([min(flowrate_lpm - flowrate_err_lpm) - 0.8, ...
      max(flowrate_lpm + flowrate_err_lpm) + 0.8]);
set(gca, 'XTick', xPos, ...
         'XTickLabel', arrayfun(@(v) sprintf('%.3g', v), kD, 'UniformOutput', false));

% Aesthetics
set(gca, 'FontName','Times New Roman', ...
         'FontSize',18, ...
         'LineWidth',1.4, ...
         'Box','on', ...
         'TickDir','in', ...
         'XScale','linear', ...
         'XMinorTick','on', ...
         'YMinorTick','on');

xlabel(xlab, 'FontSize',20, ...
    'FontName','Times New Roman', ...
    'FontAngle','italic', ...
    'Interpreter','latex');
ylabel(ylab, 'FontSize',20, ...
    'FontName','Times New Roman', ...
    'FontAngle','italic', ...
    'Interpreter','none');
titleHandle = title(strrep(plotTitle,'_',' '), ...
      'FontSize',22, ...
      'FontName','Times New Roman', ...
      'FontAngle','italic', ...
      'Interpreter','none');

legend('Location','northwest', ...
    'FontSize',16, ...
    'FontName','Times New Roman', ...
    'Interpreter','none');

hold off;

% -------------------------------------------------------
% Save Figure (simple + robust)
% -------------------------------------------------------
if ~exist(savePath, 'dir')
    mkdir(savePath);
end

pngFile = fullfile(savePath, 'flowrate.png');
svgFile = fullfile(savePath, 'flowrate.svg');

saveas(F, pngFile);              % saves PNG
titleHandle.String = '';
saveas(F, svgFile);              % saves SVG
titleHandle.String = strrep(plotTitle,'_',' ');

fprintf('Saved:\n%s\n%s\n', pngFile, svgFile);
